#!/bin/bash
#==================================
clear
echo "Eddy test case"
#======================================================================
# SETTING UP THE RUN
#======================================================================
cd data
python3 make_eddy.py
python3 make_init.py
cd ..

#======================================================================
# RUNNING THE MODEL
#======================================================================
export OMP_NUM_THREADS=1
#==================================
# Namelist variables
export runid="eddy"

# 2D/3D
export run_3d=False

# Dry run
export dry_run=False

# Hydrodynamic data
export getmpath="${PWD}/data/data"
export topofile="${PWD}/data/eddy_topo.nc"

# Hydrodynamic data variables
export lonvarname="lon"
export latvarname="lat"
export uvarname="u"
export vvarname="v"

# Model domain
export nx=600
export ny=500
export has_subdomains=False

# Advetion + buoyancy
export do_velocity=False

# Diffusion
export do_diffusion=False

# Resuspension
export resuspension_coeff=0.0

# Biofouling
export do_biofouling=False

# Boundary interactions
export kill_beached=True
export kill_boundary=True

# Time
# Start and end dates for each run are set below
export dt=60.

# Input
export particle_init_method=1
export coordfile="${PWD}/data/ini_particles.dat"
in_hours=1000
export inputstep=`python3 -c "print(int($in_hours*3600./$dt))"`

# Output
export outputstep=10
export write_all_particles=True
export write_active_particles=False
export write_snapshot=False

# Restart
# Restart variable is set below
# Write at the end of the run (default in namelist template)
# restart_hours=1440
# export restartstep=`python3 -c "print(int($restart_hours*3600./$dt))"`
#==================================
#--------------------
RUN_DIR=${PWD}
BASE_DIR=${RUN_DIR}/../..
NML_PATH=${BASE_DIR}/nml
#--------------------
MODEL_DIR=${BASE_DIR}/bin
MODEL_BIN=${MODEL_DIR}/main
#--------------------
OUT_BASE_DIR="${RUN_DIR}/out"
#--------------------
# Entire simulation period
sim_start="2018-01-01 00:00:00"
sim_end="2018-01-01 16:20:00"
#--------------------
echo "===================="
echo "Running model:"
${MODEL_BIN} -c
#--------------------
# Set timer
tic=$(date +%s)
#--------------------
# Set run start and end dates
export run_start=$sim_start
export run_end=$sim_end
#--------------------
echo "The model is running from $run_start to $run_end"
#--------------------
# Set output directory
export outdir="${OUT_BASE_DIR}"
echo "Making output directory: $outdir"
mkdir -p ${outdir}
#--------------------
# Make namelists
${NML_PATH}/makenamelist.py -i ${NML_PATH}/nmltemplate
cp input.inp ${outdir}/.
#--------------------
# Run model
echo "Running model..."
tic_m=$(date +%s)
${MODEL_BIN}
toc_m=$(date +%s)
#--------------------
echo "Model wall time: $((toc_m-tic_m)) seconds" 
echo "===================="
#--------------------
# Copy output
echo "Copying output to run folder..."
cp ${runid}.stdout ${outdir}/.
#--------------------
toc=$(date +%s)
echo "===================="
echo "All finished!"
echo "Total time: $((toc-tic)) seconds"
echo "===================="


#======================================================================
# PLOTTING THE RESULTS
#======================================================================
python3 plot_trajectory.py